apiVersion: v1
kind: Service
metadata:
  name: {{ template "website.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "website.name" . }}
